---


- name: "Provision VPC instances."
  local_action:
    module: ec2

    instance_tags: "{{ item.tags }}"
    exact_count: "{{ item.count | default(aws_instance_count) }}"
    count_tag: "{{ item.match_tags | default(item.tags) }}"
    instance_type: "{{ item.type | default(aws_instance_type) }}"
    image: "{{ item.image_id | default(aws_instance_image_id) }}"
    region: "{{ aws_vpc_region }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_ids[item.subnet_name] }}"
    source_dest_check: "{{ item.block_nat | default(aws_instance_block_nat) }}"
    assign_public_ip: "{{ item.is_public | default(aws_instance_public) }}"
    keypair: "{{ item.ssh_keypair | default(aws_instance_ssh_keypair) }}"
    group: "{{ item.security_groups }}"
    wait: yes
  with_items: "aws_instances"
  register: ec2_result
  when: "aws_instances is defined"


# To avoid accidental deletion of a deployment... :)
# This assumes the aws-cli is available from the shell of the current execution context.
# - name: "Disable API instance termination"
#   local_action: command aws ec2 modify-instance-attribute --region {{ vpc_region }} --instance-id {{ item }} --attribute disableApiTermination --value false
#   with_items: instances.instance_ids

